# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2241f3c806c61eda6bee1ccf34687070b52998f08e1c4c8ebfc629b33fa7b515d26b8346dd2704f9f31f7456369cc76ba44483e95d1d64db50c4878edf4080d7

test:
  secret_key_base: 26f6f9bc7106638efeed5ccbd7fe3de81c9397c1b0754162167dfa90605327e73ae269cf06c02ed195e723ea6f5e1d240b588812aa5ad383acf9c40c6bbb3159

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
